#!/usr/local/bin/zsh

#
# Exports
#
export KEYTIMEOUT=1
export ZSH_TMUX_FIXTERM=true
export WORKSPACE_DIR=~/workspace
# Fix GPG https://github.com/keybase/keybase-issues/issues/2798
export GPG_TTY=$(tty)

# Function to add directories to PATH if they exist and are not already in PATH
pathadd() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    export PATH="$1:$PATH"
  fi
}

# Homebrew
if command -v brew &>/dev/null; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "Homebrew not found. Please install Homebrew."
fi

# Set up NPM global path
pathadd "/usr/local/share/npm/bin"

# NVM setup
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    nvm use
  elif [ "$node_version" != "system" ]; then
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# Add other directories to PATH
pathadd "$HOME/Library/pnpm"
pathadd "$HOME/.nvm/versions/node/v22.11.0/bin"
pathadd "/opt/homebrew/bin"
pathadd "/opt/homebrew/sbin"
pathadd "$HOME/.bin"
pathadd "/usr/local/bin"
pathadd "/usr/bin"
pathadd "/bin"
pathadd "/usr/sbin"
pathadd "/sbin"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/lib"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/macos"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew"
pathadd "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/aws"
pathadd "$HOME/.antigen/bundles/zsh-users/zsh-completions"
pathadd "$HOME/.antigen/bundles/zsh-users/zsh-autosuggestions"
pathadd "$HOME/.antigen/bundles/zsh-users/zsh-syntax-highlighting"

# Vi mode
bindkey -v

# Theme

eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/catppuccin.omp.json)"
source ~/workspace/catppuccin_mocha-zsh-syntax-highlighting.zsh

#
# Antigen config
#
source ~/.bin/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle command-not-found
antigen bundle docker
antigen bundle macos
antigen bundle brew
antigen bundle aws
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

# Neofetch

neofetch